### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nu0l** [TonyD0g/Groundhog#1]
服务端:
```
java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-8u362-ga-0ubuntu1~20.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)
```

getData目录无生成文件
```
java -jar Groundhog-0.0.9.jar 
[+] A quick build tools By TonyD0g
23/05/11 13:54:22 INFO sec.Main: start Groundhog application
23/05/11 13:54:30 INFO Network.Socket: [+] 已上钩的客户端: 117.88.1xxxx 38841
java.lang.NullPointerException
        at org.sec.utils.FileUtils.mkdir(FileUtils.java:296)
        at org.sec.utils.FileUtils.writeLines(FileUtils.java:217)
        at org.sec.Network.Socket.deceptionMysqlCMD(Socket.java:123)
        at org.sec.Network.Socket.run(Socket.java:174)
        at org.sec.Network.Socket.connect(Socket.java:35)
        at org.sec.Main.main(Main.java:17)
23/05/11 13:56:43 INFO Network.Socket: [+] 已上钩的客户端: 117xxxxxxxxx 40731
java.lang.NullPointerException
        at org.sec.utils.FileUtils.mkdir(FileUtils.java:296)
        at org.sec.utils.FileUtils.writeLines(FileUtils.java:217)
        at org.sec.Network.Socket.deceptionMysqlCMD(Socket.java:123)
        at org.sec.Network.Socket.run(Socket.java:174)
        at org.sec.Network.Socket.connect(Socket.java:35)
        at org.sec.Main.main(Main.java:17)
```

客户端:

```
mysql --version
mysql  Ver 14.14 Distrib 5.7.8-rc, for Win64 (x86_64)

mysql -h 47.xxxxxxxx -uroot -p
Enter password: ******
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
```

**Comment by TonyD0g** [comment]
可能写的有点问题，你先自己创建那几个txt文件，我下个版本修复

**Comment by TonyD0g** [comment]
0.1.2版本已修复
